### PR TITLE
Attempt to activate coveralls

### PR DESCRIPTION
**Pull request by tomdonaldson**

### CODE REVIEW

**Comment by stargaser** [comment]
I notice that in the development astropy that in `conftest.py`, instead of
```
from astropy.tests.plugins.display import (pytest_report_header,
```
there is now
```
from pytest_astropy_header.display import (pytest_report_header,
```

I tried to push this to this branch, but I don't have permission. Maybe we don't have "allow edits from maintainers" turned on?

**Comment by stargaser** [comment]
Ah, I _can_ push to this branch after all! I made a git error on the command line before (of course!).

**Comment by stargaser** [comment]
For my next try, I have commented out the test against Astropy LTS (Long Term Support) which is currently v2.x. Once Astropy 4.0 is out, it becomes the LTS version and then we can re-enable this test.

**Review by ceb8 — APPROVED** [review]

**Comment by tomdonaldson** [comment]
Thanks, @stargaser!  Do you think this change to conftest.py is something that should be changed in the astropy/package-template?

**Comment by stargaser** [comment]
@tomdonaldson I've opened #[435](https://github.com/astropy/package-template/issues/435) on the package-template repo. I'm not sure what is the best solution there, since `pytest_astropy_header` could be included as a required package to get around the problem, I think.

**Comment by stargaser** [comment]
Let me try that again to see if Github magic works: I opened https://github.com/astropy/package-template/issues/435 on the package-template repo.

**Pull request merged**
